### ISSUE TITLE
Yatopia

### ISSUE THREAD

**Issue by Titaniumtown** [Incendo/ServerLib#2]
https://github.com/NotMyFault/ServerLib/blob/f88e5a6cfbbbc108da224ed411bff5f76b50d490/src/main/java/de/notmyfault/serverlib/forks/Yatopia.java#L22

There is no recent evidence I am aware of that backs this claim up, could you elaborate or provide examples? There was once incident in august 2020, but that is about it.

**Comment by NotMyFault** [comment]
Quoting the message from our discord:
![](https://i.imgur.com/IsbglzU.png)
This library is a lazy attempt doing what EssentialsX will do for future versions https://github.com/EssentialsX/Essentials/pull/3812/files#diff-b22e2c133f5b562c453ed95c7082951d0be1739eb278d267cce1b7a0724ca966R37

**Comment by mbax** [comment]
> There is no recent evidence

> august 2020

Okay.

**Comment by Citymonstret** [comment]
https://github.com/YatopiaMC/Yatopia/issues/376

**Comment by ishland** [comment]
> [YatopiaMC/Yatopia#376](https://github.com/YatopiaMC/Yatopia/issues/376)

That issue is only present in a dev branch, not on the main branch.

**Comment by Citymonstret** [comment]
Doesn't matter. Yatopia keeps messing with things that continuously breaks compatibility with existing plugins and we don't want the burden of having to keep up with a messy server fork for no good reason. The fact that it happens at all is cause for concern, and just further strengthens our existing stance against it. The warnings will remain.

**Comment by Citymonstret** [comment]
@Titaniumtown I don't see how this is particularly amusing, but to each their own. 

I'll go ahead and close this issue as it's quite clear where we stand, and Yatopia seems more concerned about their reputation than the usability and stability of their project.

Have a good day =)
